'use client';

import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Bot, Check, Database, FileCheck, LockKeyhole, MessageSquare, Pill, Send, Stethoscope, UserRoundCheck } from 'lucide-react';
import { BrandLogo } from '@/components/ui/BrandLogo';
import { TactileButton } from '@/components/ui/TactileButton';

interface ChatMessage { role: 'user' | 'assistant'; text: string; }
const examples = ['Can I take aspirin and warfarin together?', 'What can I do after signing in?'];

export default function LandingPage() {
  const [messages, setMessages] = useState<ChatMessage[]>([{ role: 'assistant', text: 'Ask me about a medicine combination or what Vediora can do. You can try two messages before signing in.' }]);
  const [input, setInput] = useState('');
  const [remaining, setRemaining] = useState(2);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  async function send(event: FormEvent) {
    event.preventDefault();
    const question = input.trim();
    if (!question || busy || remaining <= 0) return;
    setMessages(current => [...current, { role: 'user', text: question }]); setInput(''); setBusy(true); setError('');
    try {
      const conversation = messages.slice(-6).map(message => ({ role: message.role, content: message.text }));
      const response = await fetch('/api/public/preview-chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message: question, conversation }) });
      const body = await response.json();
      if (!response.ok) {
        if (response.status === 429) { setRemaining(0); setMessages(current => [...current, { role: 'assistant', text: body.error }]); return; }
        throw new Error(body.error || 'The preview is temporarily unavailable.');
      }
      setMessages(current => [...current, { role: 'assistant', text: body.answer }]);
    } catch (error) { setError(error instanceof Error ? error.message : 'The preview is temporarily unavailable.'); }
    finally { setBusy(false); }
  }
  function useExample(value: string) { if (remaining > 0 && !busy) setInput(value); }
  return <div className="min-h-screen bg-white text-slate-950">
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6"><BrandLogo showBadge={false} /><div className="flex items-center gap-2"><Link href="/login"><TactileButton variant="secondary" size="sm">Sign in</TactileButton></Link><Link href="/signup"><TactileButton size="sm">Create account</TactileButton></Link></div></div></header>

    <main>
      <section className="relative overflow-hidden border-b border-slate-200 bg-gradient-to-b from-blue-50/70 via-white to-white"><div className="pointer-events-none absolute left-1/2 top-0 h-96 w-96 -translate-x-1/2 rounded-full bg-blue-200/30 blur-3xl"/><div className="relative mx-auto grid max-w-7xl gap-12 px-4 py-16 sm:px-6 lg:grid-cols-[1fr_0.9fr] lg:items-center lg:py-24">
        <div><h1 className="max-w-3xl text-4xl font-black tracking-tight text-slate-950 sm:text-6xl">Understand your medicines. Keep your care team in sync.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Vediora keeps your confirmed medicine list in one place, checks documented interaction records, explains medical questions with a local AI model, and lets you decide which doctor can see your information.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/signup"><TactileButton size="lg" rightIcon={<ArrowRight className="h-4 w-4"/>}>Create your workspace</TactileButton></Link><Link href="#how-it-works"><TactileButton size="lg" variant="secondary">See how it works</TactileButton></Link></div><div className="mt-8 grid max-w-xl grid-cols-2 gap-3 text-sm text-slate-600"><span className="flex items-center gap-2"><Check className="h-4 w-4 text-teal-600"/>Patient-controlled access</span><span className="flex items-center gap-2"><Check className="h-4 w-4 text-teal-600"/>Local Mistral assistant</span><span className="flex items-center gap-2"><Check className="h-4 w-4 text-teal-600"/>Database evidence</span><span className="flex items-center gap-2"><Check className="h-4 w-4 text-teal-600"/>Versioned reports</span></div></div>

        <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-2xl shadow-blue-950/10"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-600 text-white"><Bot className="h-5 w-5"/></span><div><h2 className="font-bold">Try Vediora</h2><p className="text-xs text-slate-500">Two-message guest preview</p></div></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600">{remaining} left</span></div><div className="flex min-h-80 flex-col gap-3 bg-slate-50/70 p-5" aria-live="polite">{messages.map((message,index)=><div key={index} className={`max-w-[88%] rounded-2xl px-4 py-3 text-sm leading-6 ${message.role==='user'?'ml-auto bg-blue-600 text-white':'border border-slate-200 bg-white text-slate-700 shadow-sm'}`}>{message.text}</div>)}{busy&&<div className="w-fit rounded-2xl border bg-white px-4 py-3 text-sm text-slate-500">Checking the preview database…</div>}{remaining===0&&<div className="mt-auto rounded-2xl border border-blue-200 bg-blue-50 p-4"><p className="text-sm font-semibold text-blue-950">Continue with your own medicine profile</p><p className="mt-1 text-xs leading-5 text-blue-800">Sign in to save conversations, include active medicines, and generate evidence reports.</p><Link href="/login" className="mt-3 inline-block"><TactileButton size="sm">Sign in to continue</TactileButton></Link></div>}</div>{remaining>0&&<div className="border-t bg-white p-4"><div className="mb-3 flex flex-wrap gap-2">{examples.map(example=><button key={example} onClick={()=>useExample(example)} className="rounded-full border border-slate-200 px-3 py-1.5 text-left text-xs text-slate-600 hover:border-blue-300 hover:bg-blue-50">{example}</button>)}</div><form onSubmit={send} className="flex items-end gap-2 rounded-xl border border-slate-300 bg-white p-2 focus-within:border-blue-500 focus-within:ring-2 focus-within:ring-blue-100"><label htmlFor="guest-question" className="sr-only">Ask the guest medicine assistant</label><textarea id="guest-question" value={input} onChange={event=>setInput(event.target.value)} maxLength={500} rows={2} placeholder="Ask about medicines or Vediora…" className="min-h-12 flex-1 resize-none border-0 px-2 py-1 text-sm outline-none"/><TactileButton type="submit" size="sm" disabled={!input.trim()} isLoading={busy} aria-label="Send guest question" leftIcon={<Send className="h-4 w-4"/>}>Send</TactileButton></form>{error&&<p role="alert" className="mt-2 text-xs text-red-600">{error}</p>}<p className="mt-2 text-[11px] leading-4 text-slate-400">Preview answers are educational. Missing database records do not prove safety.</p></div>}</div>
      </div></section>

      <section id="how-it-works" className="mx-auto max-w-7xl px-4 py-20 sm:px-6"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-widest text-blue-600">How Vediora works</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">One medicine record, connected patient and doctor workspaces</h2><p className="mt-4 text-slate-600">The product keeps the important steps clear and reviewable. Database findings stay separate from AI explanations.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[
        [Pill,'Confirm your medicines','Save active medicines and reviewed prescription entries using names matched to the imported catalog.'],
        [Database,'Check documented pairs','Vediora checks every recognized medicine pair against the interaction database and shows missing coverage as uncertainty.'],
        [MessageSquare,'Ask in plain language','Local Mistral explains medicines and general medical topics while database records remain authoritative for interactions.'],
        [FileCheck,'Keep evidence versions','Generate printable patient or doctor reports that preserve the medicines, findings, sources, and missing pairs used.'],
      ].map(([Icon,title,copy])=><article key={String(title)} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-blue-700"><Icon className="h-5 w-5"/></span><h3 className="mt-5 text-lg font-bold">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{String(copy)}</p></article>)}</div></section>

      <section className="border-y border-slate-200 bg-slate-50"><div className="mx-auto grid max-w-7xl gap-6 px-4 py-20 sm:px-6 lg:grid-cols-2"><article className="rounded-3xl border border-blue-200 bg-white p-8"><div className="flex items-center justify-between"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">For patients</span><UserRoundCheck className="h-6 w-6 text-blue-600"/></div><h2 className="mt-5 text-2xl font-black">Your medicine safety workspace</h2><ul className="mt-5 space-y-3 text-sm text-slate-600"><li className="flex gap-2"><Check className="mt-0.5 h-4 w-4 text-teal-600"/>Maintain active and discontinued medicine history</li><li className="flex gap-2"><Check className="mt-0.5 h-4 w-4 text-teal-600"/>Save confirmed prescriptions and evidence reports</li><li className="flex gap-2"><Check className="mt-0.5 h-4 w-4 text-teal-600"/>Approve, deny, or revoke doctor access</li><li className="flex gap-2"><Check className="mt-0.5 h-4 w-4 text-teal-600"/>Continue private, remembered medical chats</li></ul><Link href="/signup" className="mt-7 inline-block"><TactileButton>Start as a patient</TactileButton></Link></article><article className="rounded-3xl border border-teal-200 bg-white p-8"><div className="flex items-center justify-between"><span className="rounded-full bg-teal-50 px-3 py-1 text-xs font-bold text-teal-700">For doctors</span><Stethoscope className="h-6 w-6 text-teal-600"/></div><h2 className="mt-5 text-2xl font-black">Consent-based clinical review</h2><ul className="mt-5 space-y-3 text-sm text-slate-600"><li className="flex gap-2"><Check className="mt-0.5 h-4 w-4 text-teal-600"/>Request access using the patient’s account email</li><li className="flex gap-2"><Check className="mt-0.5 h-4 w-4 text-teal-600"/>View only currently approved patient records</li><li className="flex gap-2"><Check className="mt-0.5 h-4 w-4 text-teal-600"/>Run database-grounded medicine reviews</li><li className="flex gap-2"><Check className="mt-0.5 h-4 w-4 text-teal-600"/>Open versioned evidence reports</li></ul><Link href="/signup" className="mt-7 inline-block"><TactileButton variant="success">Register as a doctor</TactileButton></Link></article></div></section>

      <section className="mx-auto max-w-5xl px-4 py-20 text-center sm:px-6"><LockKeyhole className="mx-auto h-8 w-8 text-blue-600"/><h2 className="mt-5 text-3xl font-black">Ready to use your own medicine profile?</h2><p className="mx-auto mt-4 max-w-2xl text-slate-600">Create an account to save medicines, remember chats, manage doctor consent, and keep evidence reports connected to one workspace.</p><div className="mt-7 flex justify-center gap-3"><Link href="/signup"><TactileButton size="lg">Create account</TactileButton></Link><Link href="/login"><TactileButton size="lg" variant="secondary">Sign in</TactileButton></Link></div></section>
    </main>
    <footer className="border-t border-slate-200 bg-slate-950 text-slate-300"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-4 py-8 sm:flex-row sm:items-center sm:justify-between sm:px-6"><BrandLogo showBadge={false} className="[&_span]:text-white"/><p className="max-w-xl text-xs leading-5 text-slate-400">Vediora is an educational medication-support tool. Confirm personal treatment decisions with a qualified doctor or pharmacist.</p></div></footer>
  </div>;
}
