'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { FileCheck } from 'lucide-react';
import { DoctorReportView, type DoctorReport } from '@/components/doctor/DoctorReportView';
import { TactileButton } from '@/components/ui/TactileButton';

export default function DoctorReportsPage(){
  const [reports,setReports]=useState<DoctorReport[]>([]);const [selectedId,setSelectedId]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  useEffect(()=>{fetch('/api/doctor/reports',{cache:'no-store'}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);setReports(b.reports||[]);setSelectedId(b.reports?.[0]?.id||'');}).catch(e=>setError(e.message||'Could not load reports.')).finally(()=>setLoading(false));},[]);
  const selected=useMemo(()=>reports.find(r=>r.id===selectedId)||reports[0],[reports,selectedId]);
  return <div className="space-y-6"><header className="rounded-2xl border bg-white p-6"><p className="text-xs font-semibold uppercase text-teal-700">Doctor workspace</p><h1 className="mt-2 text-2xl font-bold">Evidence-linked reports</h1><p className="mt-2 text-sm text-slate-600">Reports appear only while the patient’s approval remains active. Each version preserves the medicines, findings, missing pairs, and evidence references used when it was generated.</p></header>{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{loading?<p className="text-sm text-slate-500">Loading approved reports…</p>:reports.length===0?<div className="rounded-xl border border-dashed bg-white p-10 text-center"><FileCheck className="mx-auto h-8 w-8 text-slate-400"/><h2 className="mt-3 font-bold">No accessible reports</h2><p className="mt-1 text-sm text-slate-500">Generate a review for an approved patient first.</p><Link href="/doctor/analysis" className="mt-4 inline-block"><TactileButton>Open clinical review</TactileButton></Link></div>:<div className="grid gap-5 lg:grid-cols-[260px_1fr]"><aside className="no-print h-fit rounded-xl border bg-white p-3"><h2 className="px-2 py-2 text-sm font-bold">Report history</h2><div className="space-y-2">{reports.map(r=><button key={r.id} onClick={()=>setSelectedId(r.id)} className={`w-full rounded-lg border p-3 text-left ${selected?.id===r.id?'border-teal-300 bg-teal-50':'border-slate-200 hover:bg-slate-50'}`}><span className="block text-sm font-bold">{r.patient_name}</span><span className="mt-1 block text-xs text-slate-500">Version {r.version} · {new Date(r.created_at).toLocaleDateString()}</span></button>)}</div></aside>{selected&&<DoctorReportView report={selected}/>}</div>}</div>;
}
