'use client';
import { AlertTriangle, ExternalLink, Printer, ShieldCheck } from 'lucide-react';
import { TactileButton } from '@/components/ui/TactileButton';

export interface DoctorReport {
  id:string; patient_id:string; patient_name:string; version:number; overall_severity:string; summary:string; generator_role:string|null; created_at:string;
  evidence_snapshot:{ medicines:Array<{drug_id:number;medicine_name:string}>; findings:Array<{id:number;pair:string;severity:string|null;description:string|null;clinicalEffect:string|null;evidenceSource:string|null;referenceUrl:string|null}>; missingPairs:string[]; limitation:string };
}
const style=(severity:string)=>severity.toLowerCase()==='major'?'border-red-200 bg-red-50 text-red-800':severity.toLowerCase()==='moderate'?'border-amber-200 bg-amber-50 text-amber-900':'border-blue-200 bg-blue-50 text-blue-800';
export function DoctorReportView({report}:{report:DoctorReport}){
  return <article className="rounded-2xl border bg-white p-6 sm:p-8"><div className="flex flex-wrap justify-between gap-4 border-b pb-5"><div><p className="text-xs font-semibold uppercase text-teal-700">Clinical evidence review · Version {report.version}</p><h2 className="mt-2 text-xl font-bold">{report.patient_name}</h2><p className="mt-1 text-xs text-slate-500">Generated {new Date(report.created_at).toLocaleString()} · {report.generator_role==='doctor'?'Clinician generated':'Patient generated'}</p></div><div className="flex items-center gap-2"><span className={`rounded-lg border px-3 py-1.5 text-xs font-bold ${style(report.overall_severity)}`}>{report.overall_severity}</span><TactileButton className="no-print" size="sm" variant="secondary" onClick={()=>window.print()} leftIcon={<Printer className="h-4 w-4"/>}>Print</TactileButton></div></div>
    <p className="mt-5 rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-700">{report.summary}</p>
    <section className="mt-6"><h3 className="flex items-center gap-2 font-bold"><ShieldCheck className="h-5 w-5 text-teal-600"/>Medicines checked</h3><div className="mt-3 flex flex-wrap gap-2">{report.evidence_snapshot.medicines.map(m=><span key={m.drug_id} className="rounded-lg border border-teal-200 bg-teal-50 px-3 py-1.5 text-xs font-semibold text-teal-800">{m.medicine_name}</span>)}</div></section>
    <section className="mt-6 space-y-3"><h3 className="font-bold">Database findings ({report.evidence_snapshot.findings.length})</h3>{report.evidence_snapshot.findings.length===0?<p className="rounded-xl border border-dashed p-4 text-sm text-slate-600">No record was found for these pairs. This does not establish safety.</p>:report.evidence_snapshot.findings.map(f=><div key={f.id} className={`rounded-xl border p-4 ${style(f.severity||'unknown')}`}><div className="flex justify-between gap-3"><h4 className="font-bold">{f.pair}</h4><span className="text-xs font-bold uppercase">{f.severity||'Not recorded'}</span></div>{f.description&&<p className="mt-3 text-sm leading-6">{f.description}</p>}{f.clinicalEffect&&<p className="mt-2 text-sm"><strong>Clinical effect:</strong> {f.clinicalEffect}</p>}<p className="mt-3 text-xs">Source: {f.evidenceSource||'Imported interaction record'} {f.referenceUrl&&<a href={f.referenceUrl} target="_blank" rel="noreferrer" className="ml-2 inline-flex items-center gap-1 font-bold underline">Reference <ExternalLink className="h-3 w-3"/></a>}</p></div>)}</section>
    {report.evidence_snapshot.missingPairs.length>0&&<section className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4"><h3 className="flex items-center gap-2 font-bold text-amber-950"><AlertTriangle className="h-5 w-5"/>Pairs without records</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-amber-900">{report.evidence_snapshot.missingPairs.map(pair=><li key={pair}>{pair}</li>)}</ul></section>}
    <p className="mt-6 border-t pt-5 text-xs leading-5 text-slate-500">{report.evidence_snapshot.limitation}</p>
  </article>;
}
