import { randomUUID } from 'node:crypto';
import pg from 'pg';

if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL is not configured.');
const databaseUrl = new URL(process.env.DATABASE_URL); databaseUrl.searchParams.delete('sslmode');
const client = new pg.Client({ connectionString: databaseUrl.toString(), ssl: { rejectUnauthorized: false } });
await client.connect();
try {
  await client.query('begin');
  const accounts = await client.query<{ id:string; account_type:'patient'|'doctor' }>(`select id,account_type from public.vediora_profiles where account_type in ('patient','doctor') order by created_at desc`);
  const patient = accounts.rows.find(row => row.account_type === 'patient'); const doctor = accounts.rows.find(row => row.account_type === 'doctor');
  if (!patient || !doctor) throw new Error('A patient account and a doctor account are both required before seeding the video demo.');
  const drugs = await client.query<{drug_id:number;name:string}>(`select drug_id,coalesce(generic_name,ingredient_name,brand_name) name from public.drugs where lower(trim(coalesce(generic_name,'')))=any($1::text[]) order by drug_id`, [['acetylsalicylic acid','warfarin','metformin']]);
  if (drugs.rows.length < 3) throw new Error('The required demo medicines are missing from the imported catalog.');
  const details:Record<string,{dosage:string;frequency:string}> = { 'acetylsalicylic acid':{dosage:'75 mg',frequency:'Once daily'}, warfarin:{dosage:'5 mg',frequency:'Once daily'}, metformin:{dosage:'500 mg',frequency:'Twice daily with meals'} };
  for (const drug of drugs.rows) { const detail=details[drug.name.toLowerCase()]||{dosage:'As prescribed',frequency:'As prescribed'}; await client.query(`insert into public.vediora_patient_medicines (id,patient_id,drug_id,medicine_name,dosage,frequency,notes,source,started_at) values ($1,$2,$3,$4,$5,$6,'Synthetic record for product demonstration.','prescription',current_date-30) on conflict (patient_id,drug_id) where status='active' do update set dosage=excluded.dosage,frequency=excluded.frequency`,[randomUUID(),patient.id,drug.drug_id,drug.name,detail.dosage,detail.frequency]); }
  let prescription = await client.query<{id:string}>(`select id from public.vediora_patient_prescriptions where patient_id=$1 and notes='VIDEO_DEMO_RECORD' limit 1`,[patient.id]);
  if (!prescription.rows[0]) { const id=randomUUID(); await client.query(`insert into public.vediora_patient_prescriptions (id,patient_id,prescriber_name,prescribed_on,source_type,notes,status) values ($1,$2,'Dr. Meera Shah',current_date-14,'manual','VIDEO_DEMO_RECORD','confirmed')`,[id,patient.id]); for(const drug of drugs.rows){const detail=details[drug.name.toLowerCase()];await client.query(`insert into public.vediora_prescription_items (id,prescription_id,drug_id,medicine_name,dosage,frequency,duration,instructions,confirmed_by_patient,added_to_profile) values ($1,$2,$3,$4,$5,$6,'30 days','Take only as prescribed.',true,true)`,[randomUUID(),id,drug.drug_id,drug.name,detail.dosage,detail.frequency]);} prescription={rows:[{id}] } as typeof prescription; }
  let access = await client.query<{id:string;status:string}>(`select id,status from public.vediora_access_requests where doctor_id=$1 and patient_id=$2 and status in ('approved','pending') order by requested_at desc limit 1`,[doctor.id,patient.id]);
  if (!access.rows[0]) { const id=randomUUID(); await client.query(`insert into public.vediora_access_requests (id,doctor_id,patient_id,status,request_message,responded_at) values ($1,$2,$3,'approved','Medication review for the product demonstration.',now())`,[id,doctor.id,patient.id]); await client.query(`insert into public.vediora_access_events (request_id,actor_id,event_type) values ($1,$2,'approved')`,[id,patient.id]); }
  else if(access.rows[0].status==='pending'){await client.query(`update public.vediora_access_requests set status='approved',responded_at=now() where id=$1`,[access.rows[0].id]);await client.query(`insert into public.vediora_access_events (request_id,actor_id,event_type) values ($1,$2,'approved')`,[access.rows[0].id,patient.id]);}
  const existingReport=await client.query(`select 1 from public.vediora_safety_reports where patient_id=$1 and evidence_snapshot->>'demo'='video'`,[patient.id]);
  if(!existingReport.rows[0]){const ids=drugs.rows.map(row=>row.drug_id);const interactions=await client.query<{interaction_id:number;drug1_id:number;drug2_id:number;a:string;b:string;severity:string|null;description:string|null;clinical_effect:string|null;evidence_source:string|null;reference_url:string|null}>(`select i.interaction_id,i.drug1_id,i.drug2_id,coalesce(d1.generic_name,d1.ingredient_name,d1.brand_name) a,coalesce(d2.generic_name,d2.ingredient_name,d2.brand_name) b,i.severity,i.description,i.clinical_effect,i.evidence_source,i.reference_url from public.drug_interactions i join public.drugs d1 on d1.drug_id=i.drug1_id join public.drugs d2 on d2.drug_id=i.drug2_id where i.drug1_id=any($1::int[]) and i.drug2_id=any($1::int[]) order by case lower(coalesce(i.severity,'')) when 'major' then 1 when 'moderate' then 2 when 'minor' then 3 else 4 end`,[ids]);const key=(a:number,b:number)=>a<b?`${a}:${b}`:`${b}:${a}`;const recorded=new Set(interactions.rows.map(row=>key(row.drug1_id,row.drug2_id)));const missingPairs:string[]=[];for(let a=0;a<drugs.rows.length;a++)for(let b=a+1;b<drugs.rows.length;b++)if(!recorded.has(key(drugs.rows[a].drug_id,drugs.rows[b].drug_id)))missingPairs.push(`${drugs.rows[a].name} + ${drugs.rows[b].name}`);const rank:Record<string,number>={major:3,moderate:2,minor:1};let severity='No documented interaction';for(const row of interactions.rows)if(row.severity&&(rank[row.severity.toLowerCase()]||0)>(rank[severity.toLowerCase()]||0))severity=row.severity;await client.query('select pg_advisory_xact_lock(hashtextextended($1,0))',[patient.id]);const version=await client.query<{version:number}>('select coalesce(max(version),0)+1 version from public.vediora_safety_reports where patient_id=$1',[patient.id]);const snapshot={demo:'video',medicines:drugs.rows.map(row=>({drug_id:row.drug_id,medicine_name:row.name})),findings:interactions.rows.map(row=>({id:row.interaction_id,pair:`${row.a} + ${row.b}`,severity:row.severity,type:null,description:row.description,clinicalEffect:row.clinical_effect&&row.clinical_effect.length<800?row.clinical_effect:null,evidenceSource:row.evidence_source,referenceUrl:row.reference_url})),missingPairs,limitation:'A missing database record does not prove that a combination is safe. Do not change prescribed medicine without a doctor or pharmacist.'};await client.query(`insert into public.vediora_safety_reports (id,patient_id,prescription_id,version,overall_severity,summary,evidence_snapshot,generated_by,generator_role) values ($1,$2,$3,$4,$5,$6,$7::jsonb,$2,'patient')`,[randomUUID(),patient.id,prescription.rows[0].id,version.rows[0].version,severity,`Demo review checked ${drugs.rows.length} medicines and found ${interactions.rows.length} documented interaction record${interactions.rows.length===1?'':'s'}.`,JSON.stringify(snapshot)]);}
  for(const owner of [{...patient,role:'patient' as const},{...doctor,role:'doctor' as const}]){const title='Demo: aspirin and warfarin';const exists=await client.query(`select 1 from public.vediora_chat_conversations where owner_id=$1 and workspace_role=$2 and title=$3`,[owner.id,owner.role,title]);if(!exists.rows[0]){const conversationId=randomUUID();await client.query(`insert into public.vediora_chat_conversations (id,owner_id,workspace_role,title) values ($1,$2,$3,$4)`,[conversationId,owner.id,owner.role,title]);await client.query(`insert into public.vediora_chat_messages (id,conversation_id,role,content,created_at) values ($1,$2,'user','Can I take aspirin and warfarin together?',now()-interval '1 second'),($3,$2,'assistant','Vediora found a documented Major interaction record for acetylsalicylic acid and warfarin. Warfarin may increase the anticoagulant activity of acetylsalicylic acid. Do not change either medicine without speaking with the prescribing clinician or pharmacist.',now())`,[randomUUID(),conversationId,randomUUID()]);}}
  await client.query('commit');
  console.log(JSON.stringify({ patientAccounts:accounts.rows.filter(row=>row.account_type==='patient').length,doctorAccounts:accounts.rows.filter(row=>row.account_type==='doctor').length,medicinesSeeded:drugs.rows.length,prescriptionSeeded:true,approvedAccessReady:true,reportReady:true,chatPreviewsReady:2 }));
} catch(error){await client.query('rollback');throw error;} finally {await client.end();}
